### ISSUE TITLE
Does it require Speedgoat IO Blockset?

### ISSUE THREAD

**Issue by birajstha** [sync2brain/bossdevice-api-matlab#39]
Hi,
I have been using Matlab 2021a with Speedgoat IO Boockset 9.6.0, and I could connect to BOSS device with no issues.
However, When I try to install this API, I get warning that it's not supported/compatible with Matlab 2021a. Regardless it installs fine and I think works fine too.

Yesterday I tried on another PC with Matlab 2023b. The API installs fine, but I cannot connect to the device. I could however create an object with bd = bossdevice(). It just wont connect when bd.start or bd.initialize. 

So my question is 
1. Do I need Speedgoat IO Blockset for Matlab 2023 as well, which is not listed in the requirements?
2. Is it okay to use this API with Matlab 2021a? 

Thank you in advance.

**Comment by umair-hassan** [comment]
Hi Biraj youll need to install 23 blockset and new API. 

21a API is not compatible with 23 API.

**Comment by birajstha** [comment]
Hi Umair,
Thank you so much for the answers. 1 more request.
Could you please provide me a link to download the 2023 blockset?  I only have link for 2021
Thank you

**Comment by umair-hassan** [comment]
The latest installer app from downloads page of sync2brain website takes care of it - youll not be required to set it up manualy.

**Comment by birajstha** [comment]
Do you mean the latest API installer on this page? 
because the downloads page after password takes me to the Mathworks API page.

**Comment by umair-hassan** [comment]
Yes!

**Comment by pablorcum** [comment]
There was an issue with one path missing in R2023b. Please update to the bossdevice API toolbox v0.7.3 or later if you are using R2023b.

**Comment by birajstha** [comment]
Hi @pablorcum ,
Thank you for the help. I have same issue after this update.
No progress so far.
I see path was added but the path is empty.. am I missing anything?

**Comment by pablorcum** [comment]
Please send a message to support@sync2brain.com and we will arrange a call so that we can see how your setup looks like.
