### ISSUE TITLE
"manualPulse" method does not appear to be implemented in API

### ISSUE THREAD

**Issue by hcps-ninds** [sync2brain/bossdevice-api-matlab#6]
The method [5.3. manualPulse](described here https://usermanual.sync2brain.com/4_api_documentation.html#manualpulse and used in demo scripts) does not appear to be implemented in the API for 2017b or 2021a.

**Comment by umair-hassan** [comment]
We apologize for any confusion caused. Previously, the manualPulse method was used. The manualTrigger property has been replaced by this one. There will be a fix for this mistake in the documentation in the upcoming release.
