### ISSUE TITLE
Distribute API as toolbox

### ISSUE THREAD

**Issue by pablorcum** [sync2brain/bossdevice-api-matlab#7]
MATLAB offers off-the-shelf functionality to create, package and distribute your own toolboxes. We should use [this functionality](https://www.mathworks.com/help/matlab/creating-help.html?s_tid=CRUX_lftnav) to enable packaging and distribution of the project as toolbox.

We must consider as well the [best practices](https://blogs.mathworks.com/matlab/2023/06/15/mathworks-releases-best-practices-for-matlab-toolbox-development/) for MATLAB toolbox deployment.

**Comment by rcgob** [comment]
Hi I have added a new branch to address this Issue. The new branch reorganizes the repo structure to align with matlab toolbox best practices and includes a matlab function that generates a toolbox installer.

Here is an example of an installer generated by the new function:

[bossdevice-toolbox-installer.zip](https://github.com/sync2brain/bossdevice-api-matlab/files/12196036/bossdevice-toolbox-installer.zip)

There are however a couple of things that need to be discussed concerning software and add-on requirements for the toolbox.

**Comment by pablorcum** [comment]
@rcgob Can you please create a draft pull request and add me as reviewer?
